/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddTaskRouteImport } from './routes/add-task'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as BuildingRouteImport } from './routes/building'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as CompleteTicketRouteImport } from './routes/complete-ticket'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EditMemberRouteImport } from './routes/edit-member'
import { Route as EditTaskRouteImport } from './routes/edit-task'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as FacilityRouteImport } from './routes/facility'
import { Route as GoogleSignInRouteImport } from './routes/google-sign-in'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RepairsRouteImport } from './routes/repairs'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SiteRouteImport } from './routes/site'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TeamMembersRouteImport } from './routes/team-members'
import { Route as TrainingRouteImport } from './routes/training'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddTaskRoute = AddTaskRouteImport.update({
  id: '/add-task',
  path: '/add-task',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingRoute = BuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteTicketRoute = CompleteTicketRouteImport.update({
  id: '/complete-ticket',
  path: '/complete-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EditMemberRoute = EditMemberRouteImport.update({
  id: '/edit-member',
  path: '/edit-member',
  getParentRoute: () => rootRouteImport,
} as any)
const EditTaskRoute = EditTaskRouteImport.update({
  id: '/edit-task',
  path: '/edit-task',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityRoute = FacilityRouteImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleSignInRoute = GoogleSignInRouteImport.update({
  id: '/google-sign-in',
  path: '/google-sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairsRoute = RepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamMembersRoute = TeamMembersRouteImport.update({
  id: '/team-members',
  path: '/team-members',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-task': typeof AddTaskRoute
  '/assets': typeof AssetsRoute
  '/audit-log': typeof AuditLogRoute
  '/building': typeof BuildingRoute
  '/complete': typeof CompleteRoute
  '/complete-ticket': typeof CompleteTicketRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/edit-member': typeof EditMemberRoute
  '/edit-task': typeof EditTaskRoute
  '/equipment': typeof EquipmentRoute
  '/facility': typeof FacilityRoute
  '/google-sign-in': typeof GoogleSignInRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/repairs': typeof RepairsRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site': typeof SiteRoute
  '/team': typeof TeamRoute
  '/team-members': typeof TeamMembersRoute
  '/training': typeof TrainingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-task': typeof AddTaskRoute
  '/assets': typeof AssetsRoute
  '/audit-log': typeof AuditLogRoute
  '/building': typeof BuildingRoute
  '/complete': typeof CompleteRoute
  '/complete-ticket': typeof CompleteTicketRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/edit-member': typeof EditMemberRoute
  '/edit-task': typeof EditTaskRoute
  '/equipment': typeof EquipmentRoute
  '/facility': typeof FacilityRoute
  '/google-sign-in': typeof GoogleSignInRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/repairs': typeof RepairsRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site': typeof SiteRoute
  '/team': typeof TeamRoute
  '/team-members': typeof TeamMembersRoute
  '/training': typeof TrainingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-task': typeof AddTaskRoute
  '/assets': typeof AssetsRoute
  '/audit-log': typeof AuditLogRoute
  '/building': typeof BuildingRoute
  '/complete': typeof CompleteRoute
  '/complete-ticket': typeof CompleteTicketRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/edit-member': typeof EditMemberRoute
  '/edit-task': typeof EditTaskRoute
  '/equipment': typeof EquipmentRoute
  '/facility': typeof FacilityRoute
  '/google-sign-in': typeof GoogleSignInRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/repairs': typeof RepairsRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site': typeof SiteRoute
  '/team': typeof TeamRoute
  '/team-members': typeof TeamMembersRoute
  '/training': typeof TrainingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-task'
    | '/assets'
    | '/audit-log'
    | '/building'
    | '/complete'
    | '/complete-ticket'
    | '/compliance'
    | '/dashboard'
    | '/documents'
    | '/edit-member'
    | '/edit-task'
    | '/equipment'
    | '/facility'
    | '/google-sign-in'
    | '/import'
    | '/login'
    | '/repairs'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/signup'
    | '/site'
    | '/team'
    | '/team-members'
    | '/training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-task'
    | '/assets'
    | '/audit-log'
    | '/building'
    | '/complete'
    | '/complete-ticket'
    | '/compliance'
    | '/dashboard'
    | '/documents'
    | '/edit-member'
    | '/edit-task'
    | '/equipment'
    | '/facility'
    | '/google-sign-in'
    | '/import'
    | '/login'
    | '/repairs'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/signup'
    | '/site'
    | '/team'
    | '/team-members'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/add-task'
    | '/assets'
    | '/audit-log'
    | '/building'
    | '/complete'
    | '/complete-ticket'
    | '/compliance'
    | '/dashboard'
    | '/documents'
    | '/edit-member'
    | '/edit-task'
    | '/equipment'
    | '/facility'
    | '/google-sign-in'
    | '/import'
    | '/login'
    | '/repairs'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/signup'
    | '/site'
    | '/team'
    | '/team-members'
    | '/training'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddTaskRoute: typeof AddTaskRoute
  AssetsRoute: typeof AssetsRoute
  AuditLogRoute: typeof AuditLogRoute
  BuildingRoute: typeof BuildingRoute
  CompleteRoute: typeof CompleteRoute
  CompleteTicketRoute: typeof CompleteTicketRoute
  ComplianceRoute: typeof ComplianceRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  EditMemberRoute: typeof EditMemberRoute
  EditTaskRoute: typeof EditTaskRoute
  EquipmentRoute: typeof EquipmentRoute
  FacilityRoute: typeof FacilityRoute
  GoogleSignInRoute: typeof GoogleSignInRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  RepairsRoute: typeof RepairsRoute
  ReportsRoute: typeof ReportsRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SiteRoute: typeof SiteRoute
  TeamRoute: typeof TeamRoute
  TeamMembersRoute: typeof TeamMembersRoute
  TrainingRoute: typeof TrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-task': {
      id: '/add-task'
      path: '/add-task'
      fullPath: '/add-task'
      preLoaderRoute: typeof AddTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building': {
      id: '/building'
      path: '/building'
      fullPath: '/building'
      preLoaderRoute: typeof BuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-ticket': {
      id: '/complete-ticket'
      path: '/complete-ticket'
      fullPath: '/complete-ticket'
      preLoaderRoute: typeof CompleteTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-member': {
      id: '/edit-member'
      path: '/edit-member'
      fullPath: '/edit-member'
      preLoaderRoute: typeof EditMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-task': {
      id: '/edit-task'
      path: '/edit-task'
      fullPath: '/edit-task'
      preLoaderRoute: typeof EditTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility': {
      id: '/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof FacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-sign-in': {
      id: '/google-sign-in'
      path: '/google-sign-in'
      fullPath: '/google-sign-in'
      preLoaderRoute: typeof GoogleSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repairs': {
      id: '/repairs'
      path: '/repairs'
      fullPath: '/repairs'
      preLoaderRoute: typeof RepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-members': {
      id: '/team-members'
      path: '/team-members'
      fullPath: '/team-members'
      preLoaderRoute: typeof TeamMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddTaskRoute: AddTaskRoute,
  AssetsRoute: AssetsRoute,
  AuditLogRoute: AuditLogRoute,
  BuildingRoute: BuildingRoute,
  CompleteRoute: CompleteRoute,
  CompleteTicketRoute: CompleteTicketRoute,
  ComplianceRoute: ComplianceRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  EditMemberRoute: EditMemberRoute,
  EditTaskRoute: EditTaskRoute,
  EquipmentRoute: EquipmentRoute,
  FacilityRoute: FacilityRoute,
  GoogleSignInRoute: GoogleSignInRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  RepairsRoute: RepairsRoute,
  ReportsRoute: ReportsRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SiteRoute: SiteRoute,
  TeamRoute: TeamRoute,
  TeamMembersRoute: TeamMembersRoute,
  TrainingRoute: TrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
