/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardWelcomeRouteImport } from './routes/dashboard-welcome'
import { Route as FacilityRouteImport } from './routes/facility'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MappingRouteImport } from './routes/mapping'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SiteRouteImport } from './routes/site'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as TeamRouteImport } from './routes/team'
import { Route as VerifyRouteImport } from './routes/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWelcomeRoute = DashboardWelcomeRouteImport.update({
  id: '/dashboard-welcome',
  path: '/dashboard-welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityRoute = FacilityRouteImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingRoute = MappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/complete': typeof CompleteRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-welcome': typeof DashboardWelcomeRoute
  '/facility': typeof FacilityRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/mapping': typeof MappingRoute
  '/onboarding': typeof OnboardingRoute
  '/preview': typeof PreviewRoute
  '/signup': typeof SignupRoute
  '/site': typeof SiteRoute
  '/splash': typeof SplashRoute
  '/team': typeof TeamRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/complete': typeof CompleteRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-welcome': typeof DashboardWelcomeRoute
  '/facility': typeof FacilityRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/mapping': typeof MappingRoute
  '/onboarding': typeof OnboardingRoute
  '/preview': typeof PreviewRoute
  '/signup': typeof SignupRoute
  '/site': typeof SiteRoute
  '/splash': typeof SplashRoute
  '/team': typeof TeamRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/complete': typeof CompleteRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-welcome': typeof DashboardWelcomeRoute
  '/facility': typeof FacilityRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/mapping': typeof MappingRoute
  '/onboarding': typeof OnboardingRoute
  '/preview': typeof PreviewRoute
  '/signup': typeof SignupRoute
  '/site': typeof SiteRoute
  '/splash': typeof SplashRoute
  '/team': typeof TeamRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/complete'
    | '/compliance'
    | '/dashboard'
    | '/dashboard-welcome'
    | '/facility'
    | '/import'
    | '/login'
    | '/mapping'
    | '/onboarding'
    | '/preview'
    | '/signup'
    | '/site'
    | '/splash'
    | '/team'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/complete'
    | '/compliance'
    | '/dashboard'
    | '/dashboard-welcome'
    | '/facility'
    | '/import'
    | '/login'
    | '/mapping'
    | '/onboarding'
    | '/preview'
    | '/signup'
    | '/site'
    | '/splash'
    | '/team'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/complete'
    | '/compliance'
    | '/dashboard'
    | '/dashboard-welcome'
    | '/facility'
    | '/import'
    | '/login'
    | '/mapping'
    | '/onboarding'
    | '/preview'
    | '/signup'
    | '/site'
    | '/splash'
    | '/team'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  CompleteRoute: typeof CompleteRoute
  ComplianceRoute: typeof ComplianceRoute
  DashboardRoute: typeof DashboardRoute
  DashboardWelcomeRoute: typeof DashboardWelcomeRoute
  FacilityRoute: typeof FacilityRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  MappingRoute: typeof MappingRoute
  OnboardingRoute: typeof OnboardingRoute
  PreviewRoute: typeof PreviewRoute
  SignupRoute: typeof SignupRoute
  SiteRoute: typeof SiteRoute
  SplashRoute: typeof SplashRoute
  TeamRoute: typeof TeamRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-welcome': {
      id: '/dashboard-welcome'
      path: '/dashboard-welcome'
      fullPath: '/dashboard-welcome'
      preLoaderRoute: typeof DashboardWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility': {
      id: '/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof FacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping': {
      id: '/mapping'
      path: '/mapping'
      fullPath: '/mapping'
      preLoaderRoute: typeof MappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  CompleteRoute: CompleteRoute,
  ComplianceRoute: ComplianceRoute,
  DashboardRoute: DashboardRoute,
  DashboardWelcomeRoute: DashboardWelcomeRoute,
  FacilityRoute: FacilityRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  MappingRoute: MappingRoute,
  OnboardingRoute: OnboardingRoute,
  PreviewRoute: PreviewRoute,
  SignupRoute: SignupRoute,
  SiteRoute: SiteRoute,
  SplashRoute: SplashRoute,
  TeamRoute: TeamRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
