/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddTaskRouteImport } from './routes/add-task'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as BuildingRouteImport } from './routes/building'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardWelcomeRouteImport } from './routes/dashboard-welcome'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EditTaskRouteImport } from './routes/edit-task'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as FacilityRouteImport } from './routes/facility'
import { Route as GoogleSignInRouteImport } from './routes/google-sign-in'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MappingRouteImport } from './routes/mapping'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as RepairsRouteImport } from './routes/repairs'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SiteRouteImport } from './routes/site'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as TeamRouteImport } from './routes/team'
import { Route as VerifyRouteImport } from './routes/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddTaskRoute = AddTaskRouteImport.update({
  id: '/add-task',
  path: '/add-task',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingRoute = BuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWelcomeRoute = DashboardWelcomeRouteImport.update({
  id: '/dashboard-welcome',
  path: '/dashboard-welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EditTaskRoute = EditTaskRouteImport.update({
  id: '/edit-task',
  path: '/edit-task',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityRoute = FacilityRouteImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleSignInRoute = GoogleSignInRouteImport.update({
  id: '/google-sign-in',
  path: '/google-sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingRoute = MappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairsRoute = RepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-task': typeof AddTaskRoute
  '/assets': typeof AssetsRoute
  '/audit-log': typeof AuditLogRoute
  '/building': typeof BuildingRoute
  '/complete': typeof CompleteRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-welcome': typeof DashboardWelcomeRoute
  '/documents': typeof DocumentsRoute
  '/edit-task': typeof EditTaskRoute
  '/equipment': typeof EquipmentRoute
  '/facility': typeof FacilityRoute
  '/google-sign-in': typeof GoogleSignInRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/mapping': typeof MappingRoute
  '/onboarding': typeof OnboardingRoute
  '/preview': typeof PreviewRoute
  '/repairs': typeof RepairsRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site': typeof SiteRoute
  '/splash': typeof SplashRoute
  '/team': typeof TeamRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-task': typeof AddTaskRoute
  '/assets': typeof AssetsRoute
  '/audit-log': typeof AuditLogRoute
  '/building': typeof BuildingRoute
  '/complete': typeof CompleteRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-welcome': typeof DashboardWelcomeRoute
  '/documents': typeof DocumentsRoute
  '/edit-task': typeof EditTaskRoute
  '/equipment': typeof EquipmentRoute
  '/facility': typeof FacilityRoute
  '/google-sign-in': typeof GoogleSignInRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/mapping': typeof MappingRoute
  '/onboarding': typeof OnboardingRoute
  '/preview': typeof PreviewRoute
  '/repairs': typeof RepairsRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site': typeof SiteRoute
  '/splash': typeof SplashRoute
  '/team': typeof TeamRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-task': typeof AddTaskRoute
  '/assets': typeof AssetsRoute
  '/audit-log': typeof AuditLogRoute
  '/building': typeof BuildingRoute
  '/complete': typeof CompleteRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-welcome': typeof DashboardWelcomeRoute
  '/documents': typeof DocumentsRoute
  '/edit-task': typeof EditTaskRoute
  '/equipment': typeof EquipmentRoute
  '/facility': typeof FacilityRoute
  '/google-sign-in': typeof GoogleSignInRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/mapping': typeof MappingRoute
  '/onboarding': typeof OnboardingRoute
  '/preview': typeof PreviewRoute
  '/repairs': typeof RepairsRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/site': typeof SiteRoute
  '/splash': typeof SplashRoute
  '/team': typeof TeamRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-task'
    | '/assets'
    | '/audit-log'
    | '/building'
    | '/complete'
    | '/compliance'
    | '/dashboard'
    | '/dashboard-welcome'
    | '/documents'
    | '/edit-task'
    | '/equipment'
    | '/facility'
    | '/google-sign-in'
    | '/import'
    | '/login'
    | '/mapping'
    | '/onboarding'
    | '/preview'
    | '/repairs'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/signup'
    | '/site'
    | '/splash'
    | '/team'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-task'
    | '/assets'
    | '/audit-log'
    | '/building'
    | '/complete'
    | '/compliance'
    | '/dashboard'
    | '/dashboard-welcome'
    | '/documents'
    | '/edit-task'
    | '/equipment'
    | '/facility'
    | '/google-sign-in'
    | '/import'
    | '/login'
    | '/mapping'
    | '/onboarding'
    | '/preview'
    | '/repairs'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/signup'
    | '/site'
    | '/splash'
    | '/team'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/add-task'
    | '/assets'
    | '/audit-log'
    | '/building'
    | '/complete'
    | '/compliance'
    | '/dashboard'
    | '/dashboard-welcome'
    | '/documents'
    | '/edit-task'
    | '/equipment'
    | '/facility'
    | '/google-sign-in'
    | '/import'
    | '/login'
    | '/mapping'
    | '/onboarding'
    | '/preview'
    | '/repairs'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/signup'
    | '/site'
    | '/splash'
    | '/team'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddTaskRoute: typeof AddTaskRoute
  AssetsRoute: typeof AssetsRoute
  AuditLogRoute: typeof AuditLogRoute
  BuildingRoute: typeof BuildingRoute
  CompleteRoute: typeof CompleteRoute
  ComplianceRoute: typeof ComplianceRoute
  DashboardRoute: typeof DashboardRoute
  DashboardWelcomeRoute: typeof DashboardWelcomeRoute
  DocumentsRoute: typeof DocumentsRoute
  EditTaskRoute: typeof EditTaskRoute
  EquipmentRoute: typeof EquipmentRoute
  FacilityRoute: typeof FacilityRoute
  GoogleSignInRoute: typeof GoogleSignInRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  MappingRoute: typeof MappingRoute
  OnboardingRoute: typeof OnboardingRoute
  PreviewRoute: typeof PreviewRoute
  RepairsRoute: typeof RepairsRoute
  ReportsRoute: typeof ReportsRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SiteRoute: typeof SiteRoute
  SplashRoute: typeof SplashRoute
  TeamRoute: typeof TeamRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-task': {
      id: '/add-task'
      path: '/add-task'
      fullPath: '/add-task'
      preLoaderRoute: typeof AddTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building': {
      id: '/building'
      path: '/building'
      fullPath: '/building'
      preLoaderRoute: typeof BuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-welcome': {
      id: '/dashboard-welcome'
      path: '/dashboard-welcome'
      fullPath: '/dashboard-welcome'
      preLoaderRoute: typeof DashboardWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-task': {
      id: '/edit-task'
      path: '/edit-task'
      fullPath: '/edit-task'
      preLoaderRoute: typeof EditTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility': {
      id: '/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof FacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-sign-in': {
      id: '/google-sign-in'
      path: '/google-sign-in'
      fullPath: '/google-sign-in'
      preLoaderRoute: typeof GoogleSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping': {
      id: '/mapping'
      path: '/mapping'
      fullPath: '/mapping'
      preLoaderRoute: typeof MappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repairs': {
      id: '/repairs'
      path: '/repairs'
      fullPath: '/repairs'
      preLoaderRoute: typeof RepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddTaskRoute: AddTaskRoute,
  AssetsRoute: AssetsRoute,
  AuditLogRoute: AuditLogRoute,
  BuildingRoute: BuildingRoute,
  CompleteRoute: CompleteRoute,
  ComplianceRoute: ComplianceRoute,
  DashboardRoute: DashboardRoute,
  DashboardWelcomeRoute: DashboardWelcomeRoute,
  DocumentsRoute: DocumentsRoute,
  EditTaskRoute: EditTaskRoute,
  EquipmentRoute: EquipmentRoute,
  FacilityRoute: FacilityRoute,
  GoogleSignInRoute: GoogleSignInRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  MappingRoute: MappingRoute,
  OnboardingRoute: OnboardingRoute,
  PreviewRoute: PreviewRoute,
  RepairsRoute: RepairsRoute,
  ReportsRoute: ReportsRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SiteRoute: SiteRoute,
  SplashRoute: SplashRoute,
  TeamRoute: TeamRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
